apiVersion: v1
kind: ConfigMap
metadata:
  name: front-conf
data:
  URL_GET: "http://get:8081"
  URL_POST: "http://post:8082"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: dimeder13/frontend
        envFrom:
        - configMapRef:
            name: front-conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
spec:
  type: NodePort
  ports:
  - nodePort: 30808
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: front

