apiVersion: v1
kind: ConfigMap
metadata:
  name: front-conf
  namespace: demo
data:
  URL_GET: "http://get-srv:8081"
  URL_POST: "http://post-srv:8082"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: demo
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: dimeder13/frontend
        envFrom:
        - configMapRef:
            name: front-conf
---
apiVersion: v1
kind: Service
metadata:
  name: front-srv
  namespace: demo
  labels:
    app: front
spec:
  type: NodePort
  ports:
  - nodePort: 30808
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: front

