apiVersion: v1
kind: ConfigMap
metadata:
  name: get-conf
data:
  HOST_PORT: "8081"
  ENDPOINT: "back-srv:8083"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get
  labels:
    app: get
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get
  template:
    metadata:
      name: get
      labels:
        app: get
    spec:
      containers:
      - name: get
        image: nikitasadok/go-get-service
        envFrom:
        - configMapRef:
            name: get-conf
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: get-srv
  labels:
    app: get
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: front

