apiVersion: v1
kind: ConfigMap
metadata:
  name: get-conf
  namespace: demo
data:
  HOST_PORT: "8081"
  ENDPOINT: "back-srv:8083"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get
  namespace: demo
  labels:
    app: get
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get
  template:
    metadata:
      name: get
      labels:
        app: get
    spec:
      containers:
      - name: get
        image: nikitasadok/go-get-service
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: get-conf
---
apiVersion: v1
kind: Service
metadata:
  name: get-srv
  namespace: demo
  labels:
    app: get
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: get

