# Default values for post.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 074368059797.dkr.ecr.eu-central-1.amazonaws.com/post
# repository: 893769753495.dkr.ecr.eu-central-1.amazonaws.com/nigth
  tag: latest
# pullPolicy: IfNotPresent
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

ingress:
  enabled: false
  annotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

POSTPORT: "8082"
BACKPORT: "8083"
BACKADDR: "back-srv"
